---
title: "Publications"
---


**Karg, S. T.,** Kim, M., Mitkidis, P., & Young, L. (2022). Collaborative Cheating in Hierarchical Teams:
Effects of Incentive Structure and Leader Behavior on Subordinate Behavior and Perceptions of
Leaders. Personality and Social Psychology Bulletin. https://doi.org/10.1177/01461672221090859

**Karg, S. T.**, Lim, M., & Schnall, S. (2022). Followers Forever: Prior Commitment Predicts Post-
Scandal Support of a Social Media Celebrity. Social Psychological Bulletin, 17, 1-26.
https://doi.org/10.32872/spb.8283

Andresen, M. J., **Karg, S. T. S.**, Rasmussen, S. H. R., Pradella, L., Rasmussen, J., Lindekilde, L., &
Petersen, M. B. (2022). Danskernes oplevelse af had på sociale medier. Aarhus Universitet.

Morris, B.S., Chrysochou, P., **Karg, S.T.** (2020); Optimistic vs. pessimistic endings in climate change
appeals. Humanit Soc Sci Commun 7, 82. https://doi.org/10.1057/s41599-020-00574-z

Koumaditis K., Chinello F., Mitkidis P., **Karg S.T.** (2020); Effectiveness of Virtual Versus Physical
Training: The Case of Assembly Tasks, Trainer's Verbal Assistance, and Task Complexity. IEEE
Computer Graphics and Applications 40. https://doi.org/10.1109/MCG.2020.3006330

**Karg, S.T.,** Wiener-Blotner, A., Schnall, S. (2018); Disgust Sensitivity is Associated with Heightened
Risk Perception. Journal of Risk Research. https://doi.org/10.1080/13669877.2018.1474244
